In [1]:
import basedosdados as bd

In [24]:
project_id = "teste-ic-fairness"
query = """
SELECT
  d.id_inscricao,
  d.cor_raca,
  d.ensino,
  d.estado_civil,
  d.nota_matematica,
  d.sexo,
  d.sigla_uf_prova,
  d.tipo_escola,
  q.q006 AS renda_familiar,
  q.q025 AS tem_internet,
FROM
  `basedosdados.br_inep_enem.microdados` as d

INNER JOIN `basedosdados.br_inep_enem.questionario_socioeconomico_2023` as q
  ON q.id_inscricao = d.id_inscricao

WHERE d.ano = 2023
AND d.nota_matematica IS NOT NULL
AND d.ensino IS NOT NULL
AND d.sigla_uf_prova IS NOT NULL
LIMIT 20000;
"""

df = bd.read_sql(query, billing_project_id=project_id)

print(df)

Downloading: 100%|██████████|
       id_inscricao cor_raca ensino estado_civil  nota_matematica sexo  \
0      210059134967        1      1            1            521.6    M
1      210059582187        3      1            1            432.0    F
2      210059260231        3      1            1            494.4    M
3      210059658231        3      1            1            553.9    F
4      210059753677        3      1            1            334.8    F
...             ...      ...    ...          ...              ...  ...
19995  210058612688        2      1            1            429.4    F
19996  210059224383        1      1            0            344.3    F
19997  210058326464        2      1            1            586.4    M
19998  210059342414        3      1            1            361.6    M
19999  210059617158        3      1            1            467.3    F

      sigla_uf_prova tipo_escola renda_familiar tem_internet
0                 RR           2              B            B
1                 RR           2              C            B
2                 RR           2              F            B
3                 RR           2              C            B
4                 RR           2              B            B
...              ...         ...            ...          ...
19995             TO           2              B            A
19996             TO           2              A            B
19997             TO           2              C            B
19998             TO           2              G            B
19999             TO           2              C            B

[20000 rows x 10 columns]

In [3]:
df[df.notnull().all(1)]

,id_inscricao,cor_raca,ensino,estado_civil,nota_matematica,sexo,sigla_uf_prova,tipo_escola,renda_familiar,tem_internet
0,210060737121,2,1,1,422.2,M,RR,2,B,A
1,210061381403,3,1,1,571.6,F,RR,3,B,B
2,210058258017,3,1,1,578.2,F,RR,3,D,B
3,210061090519,2,1,0,387.5,M,RR,2,G,B
4,210059413862,3,1,1,412.5,F,RR,2,B,B
...,...,...,...,...,...,...,...,...,...,...
9995,210060237077,3,1,1,389.7,F,TO,2,C,A
9996,210060437731,3,1,1,559.3,F,TO,2,B,B
9997,210060206200,1,1,1,627.6,M,TO,2,B,B
9998,210059337008,2,1,1,381.9,F,TO,2,B,B
9999,210058831807,2,1,1,343.3,F,TO,2,B,A

In [4]:
df.head()

,id_inscricao,cor_raca,ensino,estado_civil,nota_matematica,sexo,sigla_uf_prova,tipo_escola,renda_familiar,tem_internet
0,210060737121,2,1,1,422.2,M,RR,2,B,A
1,210061381403,3,1,1,571.6,F,RR,3,B,B
2,210058258017,3,1,1,578.2,F,RR,3,D,B
3,210061090519,2,1,0,387.5,M,RR,2,G,B
4,210059413862,3,1,1,412.5,F,RR,2,B,B

In [5]:
df.describe()

       nota_matematica
count     10000.000000
mean        496.684510
std         110.705559
min           0.000000
25%         413.300000
50%         486.900000
75%         573.225000
max         934.800000

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_inscricao     20000 non-null  object
 1   cor_raca         20000 non-null  object
 2   ensino           20000 non-null  object
 3   estado_civil     20000 non-null  object
 4   nota_matematica  20000 non-null  float64
 5   sexo             20000 non-null  object
 6   sigla_uf_prova   20000 non-null  object
 7   tipo_escola      20000 non-null  object
 8   renda_familiar   20000 non-null  object
 9   tem_internet     20000 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.5+ MB

In [49]:
df.nunique()

id_inscricao       20000
cor_raca               6
ensino                 2
estado_civil           5
nota_matematica     4196
sexo                   2
sigla_uf_prova        27
tipo_escola            2
renda_familiar        17
tem_internet           2
dtype: int64

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns


# sns.scatterplot(
#     x='sexo',
#     y='nota_matematica',
#     alpha=0.7,
#     data=df,
# )

# dataX = df.groupby('nota_matematica')['sexo'].value_counts()
# plt.figure(figsize=(8, 5))
# plt.hist(dataX, color='#ff5a32', edgecolor='black')

# plt.show()

# dataX

# df.hist(figsize=(20, 20), bins=25)

In [25]:
mapa_raca = {
    "0": 'Não Declarado',
    "1": 'Branca',
    "2": 'Preta',
    "3": 'Parda',
    "4": 'Amarela',
    "5": 'Indígena'
}

mapa_escola = {
    "1": 'Não Respondido',
    "2": 'Pública',
    "3": 'Privada'
}

mapa_internet = {'A': 'Não', 'B': 'Sim'}

# Substituindo no DataFrame
df_visualizacao = df.copy()
df_visualizacao['cor_raca'] = df_visualizacao['cor_raca'].map(mapa_raca)
df_visualizacao['tipo_escola'] = df_visualizacao['tipo_escola'].map(mapa_escola)
df_visualizacao['tem_internet'] = df_visualizacao['tem_internet'].map(mapa_internet)

df_visualizacao.head(10)

# Esse dataFrame facilita a visualização de alguns dados, como raça, tipo da escola, que são atributos importantes.

,id_inscricao,cor_raca,ensino,estado_civil,nota_matematica,sexo,sigla_uf_prova,tipo_escola,renda_familiar,tem_internet
0,210059134967,Branca,1,1,521.6,M,RR,Pública,B,Sim
1,210059582187,Parda,1,1,432.0,F,RR,Pública,C,Sim
2,210059260231,Parda,1,1,494.4,M,RR,Pública,F,Sim
3,210059658231,Parda,1,1,553.9,F,RR,Pública,C,Sim
4,210059753677,Parda,1,1,334.8,F,RR,Pública,B,Sim
5,210059651737,Não Declarado,1,1,401.7,M,RR,Pública,B,Sim
6,210059854549,Parda,1,1,355.6,F,RR,Pública,B,Sim
7,210060237917,Parda,1,1,420.4,F,RR,Pública,B,Sim
8,210061845856,Indígena,1,1,428.6,M,RR,Pública,A,Não
9,210059571154,Parda,1,1,727.2,F,RR,Pública,G,Sim

In [26]:
df[df['id_inscricao'].duplicated()]

Empty DataFrame
Columns: [id_inscricao, cor_raca, ensino, estado_civil, nota_matematica, sexo, sigla_uf_prova, tipo_escola, renda_familiar, tem_internet]
Index: []

In [27]:
df_visualizacao[df_visualizacao['tipo_escola'] == "Privada"].count()

# podemos ver que a minoria dos alunos é de escola particular (o que seria uma vantagem)

id_inscricao       1669
cor_raca           1669
ensino             1669
estado_civil       1669
nota_matematica    1669
sexo               1669
sigla_uf_prova     1669
tipo_escola        1669
renda_familiar     1669
tem_internet       1669
dtype: int64

In [28]:
dataEscola = df_visualizacao.groupby('tipo_escola')['nota_matematica'].mean().sort_values(ascending=False)
dataEscola

# aqui vemos também que a escola pública tem uma nota máxima maior em matemática do que a escola privada
# contudo, a privada tem uma média de quase 100 pontos maior que a pública

tipo_escola
Privada    581.33559
Pública    487.75279
Name: nota_matematica, dtype: float64

In [29]:
dataGender = df_visualizacao.groupby('sexo')['nota_matematica'].mean().sort_values(ascending=False)
dataGender

# vemos que a máxima feminina é maior que a máxima masculina
# porém a média masculina é maior que a feminina

sexo
M    518.364503
F    484.465405
Name: nota_matematica, dtype: float64

In [30]:
dataRenda = df_visualizacao.groupby('renda_familiar')['nota_matematica'].mean().sort_values(ascending=False)
dataRenda

# rendas maiores tendém a irem melhores. A renda Q (> 20 sslários minímos) tem o segundo maior máximo e a maior média
# enquanto a renda A (sem renda) tem a pior média e máxima

renda_familiar
Q    629.678082
O    621.511111
P    619.365385
N    609.361194
M    601.961039
K    585.930968
L    578.168354
I    573.103716
J    569.224868
H    564.779775
G    551.054991
F    535.684634
E    519.351216
D    510.461306
C    495.713613
B    467.174334
A    442.782423
Name: nota_matematica, dtype: float64

In [31]:
dataRace = df_visualizacao.groupby('cor_raca')['nota_matematica'].mean().sort_values(ascending=False)
dataRace

cor_raca
Branca           521.111792
Amarela          487.706250
Não Declarado    485.562500
Parda            481.152925
Preta            475.033934
Indígena         459.360606
Name: nota_matematica, dtype: float64

In [32]:
dataState = df_visualizacao.groupby('sigla_uf_prova')['nota_matematica'].mean().sort_values(ascending=False)
dataState

sigla_uf_prova
MG    520.319875
SP    519.485774
RS    517.922622
SC    517.808383
RJ    512.172330
PR    506.935929
CE    506.522524
ES    503.348997
DF    497.921864
GO    494.862565
PE    493.124596
RR    491.673810
MS    490.350183
RO    487.199394
RN    486.804091
PB    486.366667
BA    483.163942
MT    476.912968
PI    471.534281
SE    470.618045
AL    465.101087
TO    462.084977
PA    459.772296
MA    459.666927
AP    450.634161
AM    449.821542
AC    446.813043
Name: nota_matematica, dtype: float64

In [51]:
dataNet = df_visualizacao.groupby('tem_internet')['nota_matematica'].mean().sort_values(ascending=False)
dataNet

tem_internet
Sim    500.729079
Não    450.541574
Name: nota_matematica, dtype: float64

#### Regressão

Vamos começar com um modelo de Regressão para tentar prever (ou aproximar) a nota da prova de matemática de um aluno que participou do ENEM no ano de 2023. 
<br><br>
O target Y, logicamente, é a nota na prova de matemática.<br>
As outras colunas representam os features (exceto id_inscricao)

Vamos começar com um modelo simples, como um Linear Regression.\
<b>Ainda não iremos calcular métricas de fairness</b>.

In [33]:
# Como no dataset temos diversos valores que são strings, posso usar OneHot Encoder para alguns features com poucas opções, como genero,
# tipo_escola, tem_internet e ensinom que possuem apenas 2 opções
# Para atributos progressivos como renda familiar, podemos considerar um Ordinal Encoder.

# Para atributos como a renda, que possui diversas categorias, talvez um TargetEncoder possa ser útil

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

import numpy as np

np.random.seed(42)

X = df.drop(['nota_matematica', 'id_inscricao'], axis=1)
y = df['nota_matematica']

label_values = ['renda_familiar']
oh_values = ['tipo_escola', 'tem_internet', 'sexo', 'ensino', 'cor_raca', 'estado_civil', 'sigla_uf_prova']
# target_encoder_values = []

full_pipeline = ColumnTransformer(
    transformers=[
        ('label_val', OrdinalEncoder(), label_values),
        ('oh', OneHotEncoder(handle_unknown='ignore'), oh_values),
        # ('target_val', TargetEncoder(), target_encoder_values)
    ],
    remainder='drop',
)

linear_regression_model_pipeline = Pipeline([
    ('preprocessor', full_pipeline),
    ('model', LinearRegression()),
])

splitDf = KFold(random_state=42, shuffle=True)

total_mae = 0
total_rmse = 0
total_r2 = 0
for i, (train_index, test_index) in enumerate(splitDf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    linear_regression_model_pipeline.fit(X_train, y_train)

    # print(f"Treinando no fold {i + 1}")

    preds = linear_regression_model_pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    total_mae += mae
    # print(f"MAE no fold {i + 1}: {mae}")

    rmse = root_mean_squared_error(y_test, preds)
    total_rmse += rmse
    # print(f"RMSE no fold {i + 1}: {rmse}")

    r2 = r2_score(y_test, preds)
    total_r2 += r2
    # print(f"R2 no fold {i + 1}: {r2}")


print(f"\nMédia geral do MAE: {total_mae / 5}")
print(f"Média geral do RMSE: {total_rmse / 5}")
print(f"Média geral do R2: {total_r2 / 5}")

Média geral do MAE: 81.0407305841698
Média geral do RMSE: 102.80859886879702
Média geral do R2: 0.1565136261958669

In [34]:
random_forest_full_pipeline = Pipeline([
    ('preprocessor', full_pipeline),
    ('model', RandomForestRegressor(
        n_estimators=1000,
        max_features=75,
        max_depth=5
    )),
])

total_mae = 0
total_rmse = 0
total_r2 = 0
for i, (train_index, test_index) in enumerate(splitDf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    random_forest_full_pipeline.fit(X_train, y_train)

    # print(f"Treinando no fold {i + 1}")

    preds = random_forest_full_pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    total_mae += mae
    # print(f"MAE no fold {i + 1}: {mae}")

    rmse = root_mean_squared_error(y_test, preds)
    total_rmse += rmse
    # print(f"RMSE no fold {i + 1}: {rmse}")

    r2 = r2_score(y_test, preds)
    total_r2 += r2
    # print(f"R2 no fold {i + 1}: {r2}")


print(f"\nMédia geral do MAE: {total_mae / 5}")
print(f"Média geral do RMSE: {total_rmse / 5}")
print(f"Média geral do R2: {total_r2 / 5}")

Média geral do MAE: 81.61545995764712
Média geral do RMSE: 103.41181252754991
Média geral do R2: 0.14662859789303803

In [ ]:
# param_grid = {
#     'model__n_estimators': [200, 500, 1000],
#     'model__max_features': [50, 75],
#     'model__max_depth': [5, 8, 10]
# }

# grid_search = GridSearchCV(random_forest_full_pipeline, param_grid, cv=splitDf, scoring='r2', return_train_score=True)
# grid_search.fit(X_train, y_train)

In [48]:
df_analise = X_test.copy()
df_analise['real'] = y_test
df_analise['pred'] = preds

for coluna in X.columns:
    print(f"Analisando coluna: {coluna}")
    for grupo, sub_df in df_analise.groupby(coluna):
        mae_grupo = mean_absolute_error(sub_df['real'], sub_df['pred'])
        rmse_grupo = root_mean_squared_error(sub_df['real'], sub_df['pred'])
        print(f"Grupo {grupo} | Qtd Alunos: {len(sub_df)} \t | MAE: {mae_grupo:.2f} | RMSE: {rmse_grupo:.2f}")
    print()

Analisando coluna: cor_raca
Grupo 0 | Qtd Alunos: 49 	 | MAE: 80.62 | RMSE: 99.54
Grupo 1 | Qtd Alunos: 1523 	 | MAE: 88.79 | RMSE: 111.86
Grupo 2 | Qtd Alunos: 544 	 | MAE: 72.30 | RMSE: 91.20
Grupo 3 | Qtd Alunos: 1808 	 | MAE: 78.72 | RMSE: 99.54
Grupo 4 | Qtd Alunos: 52 	 | MAE: 74.62 | RMSE: 91.40
Grupo 5 | Qtd Alunos: 24 	 | MAE: 86.70 | RMSE: 98.96

Analisando coluna: ensino
Grupo 1 | Qtd Alunos: 3968 	 | MAE: 81.75 | RMSE: 103.34
Grupo 2 | Qtd Alunos: 32 	 | MAE: 75.29 | RMSE: 93.02

Analisando coluna: estado_civil
Grupo 0 | Qtd Alunos: 194 	 | MAE: 85.23 | RMSE: 106.36
Grupo 1 | Qtd Alunos: 3765 	 | MAE: 81.43 | RMSE: 103.07
Grupo 2 | Qtd Alunos: 20 	 | MAE: 85.83 | RMSE: 98.74
Grupo 3 | Qtd Alunos: 20 	 | MAE: 95.62 | RMSE: 113.25
Grupo 4 | Qtd Alunos: 1 	 | MAE: 65.45 | RMSE: 65.45

Analisando coluna: sexo
Grupo F | Qtd Alunos: 2761 	 | MAE: 78.21 | RMSE: 99.12
Grupo M | Qtd Alunos: 1239 	 | MAE: 89.48 | RMSE: 111.94

Analisando coluna: sigla_uf_prova
Grupo AC | Qtd Alunos: 22 	 | MAE: 72.21 | RMSE: 86.94
Grupo AL | Qtd Alunos: 72 	 | MAE: 80.17 | RMSE: 107.82
Grupo AM | Qtd Alunos: 88 	 | MAE: 77.41 | RMSE: 90.32
Grupo AP | Qtd Alunos: 34 	 | MAE: 75.69 | RMSE: 91.88
Grupo BA | Qtd Alunos: 394 	 | MAE: 76.38 | RMSE: 93.96
Grupo CE | Qtd Alunos: 99 	 | MAE: 74.67 | RMSE: 94.61
Grupo DF | Qtd Alunos: 66 	 | MAE: 74.40 | RMSE: 86.86
Grupo ES | Qtd Alunos: 53 	 | MAE: 92.67 | RMSE: 116.46
Grupo GO | Qtd Alunos: 199 	 | MAE: 89.56 | RMSE: 108.94
Grupo MA | Qtd Alunos: 185 	 | MAE: 70.76 | RMSE: 86.98
Grupo MG | Qtd Alunos: 407 	 | MAE: 85.37 | RMSE: 109.58
Grupo MS | Qtd Alunos: 55 	 | MAE: 75.17 | RMSE: 95.49
Grupo MT | Qtd Alunos: 63 	 | MAE: 83.07 | RMSE: 97.16
Grupo PA | Qtd Alunos: 204 	 | MAE: 73.63 | RMSE: 96.40
Grupo PB | Qtd Alunos: 86 	 | MAE: 86.36 | RMSE: 105.33
Grupo PE | Qtd Alunos: 257 	 | MAE: 83.67 | RMSE: 109.30
Grupo PI | Qtd Alunos: 126 	 | MAE: 78.62 | RMSE: 93.22
Grupo PR | Qtd Alunos: 211 	 | MAE: 87.65 | RMSE: 116.95
Grupo RJ | Qtd Alunos: 249 	 | MAE: 76.37 | RMSE: 96.03
Grupo RN | Qtd Alunos: 71 	 | MAE: 86.60 | RMSE: 114.18
Grupo RO | Qtd Alunos: 27 	 | MAE: 85.41 | RMSE: 102.29
Grupo RR | Qtd Alunos: 8 	 | MAE: 79.30 | RMSE: 98.62
Grupo RS | Qtd Alunos: 193 	 | MAE: 90.80 | RMSE: 120.64
Grupo SC | Qtd Alunos: 103 	 | MAE: 84.30 | RMSE: 107.02
Grupo SE | Qtd Alunos: 61 	 | MAE: 76.84 | RMSE: 95.56
Grupo SP | Qtd Alunos: 616 	 | MAE: 84.48 | RMSE: 103.86
Grupo TO | Qtd Alunos: 51 	 | MAE: 85.06 | RMSE: 112.37

Analisando coluna: tipo_escola
Grupo 2 | Qtd Alunos: 3681 	 | MAE: 80.87 | RMSE: 102.26
Grupo 3 | Qtd Alunos: 319 	 | MAE: 91.35 | RMSE: 114.16

Analisando coluna: renda_familiar
Grupo A | Qtd Alunos: 317 	 | MAE: 69.80 | RMSE: 91.12
Grupo B | Qtd Alunos: 1436 	 | MAE: 76.23 | RMSE: 97.88
Grupo C | Qtd Alunos: 767 	 | MAE: 81.18 | RMSE: 100.38
Grupo D | Qtd Alunos: 530 	 | MAE: 86.51 | RMSE: 107.85
Grupo E | Qtd Alunos: 283 	 | MAE: 84.19 | RMSE: 101.46
Grupo F | Qtd Alunos: 157 	 | MAE: 82.93 | RMSE: 99.87
Grupo G | Qtd Alunos: 224 	 | MAE: 97.30 | RMSE: 121.32
Grupo H | Qtd Alunos: 87 	 | MAE: 96.21 | RMSE: 133.27
Grupo I | Qtd Alunos: 50 	 | MAE: 105.34 | RMSE: 132.15
Grupo J | Qtd Alunos: 40 	 | MAE: 90.96 | RMSE: 110.83
Grupo K | Qtd Alunos: 33 	 | MAE: 87.73 | RMSE: 103.90
Grupo L | Qtd Alunos: 13 	 | MAE: 70.88 | RMSE: 87.19
Grupo M | Qtd Alunos: 14 	 | MAE: 126.34 | RMSE: 141.78
Grupo N | Qtd Alunos: 12 	 | MAE: 137.01 | RMSE: 164.83
Grupo O | Qtd Alunos: 12 	 | MAE: 129.81 | RMSE: 150.73
Grupo P | Qtd Alunos: 11 	 | MAE: 101.94 | RMSE: 117.75
Grupo Q | Qtd Alunos: 14 	 | MAE: 90.82 | RMSE: 117.64

Analisando coluna: tem_internet
Grupo A | Qtd Alunos: 410 	 | MAE: 70.94 | RMSE: 86.87
Grupo B | Qtd Alunos: 3590 	 | MAE: 82.93 | RMSE: 104.97

In [ ]:
"""
Os resultados até aqui obtidos são curiosos.
Um modelo LinearRegression teve uma performance semelhante (ou até melhor) que um modelo como Random Forest, que é teoricamente mais poderoso
e capaz de encontrar relações mais profundas nos dados. Porque isso acontece?


Podemos ver também que mesmo eles tendo um resultado semelhante, esse resultado não é muito bom. Um MAE de aproximadamente 80 para notas é
considerávelmente alto, dado que uma variação de 80 pontos em matemática pode definir se o aluno passa ou não.
Mas quando estamos focando em fairness, nem sempre queremos o modelo com maior precisão, mas sim o mais justo, por isso é importante atestar esse
modelo contra métricas de fairness.


Outra coisa é também a diferença de performance para alguns grupos. Eu notei algo contraditório, por exemplo:
    Vamos analisar a coluna "tem_internet". 3590 alunos tem acesso a internet e 410 não tem. Então, o grupo que possui internet está mais bem representado.
    Eu pensei que grupos que são menos representados normalmente tivessem um score/precisão menor, justamente porque são menos representados e, consequentemente
    o modelo não concebe tão bem as relações e padrões entre os membros desse grupo.
    Entretanto, o contrário acontece aqui, os 410 alunos que não possuem acesso a internet tem um MAE e RMSE menor do que os que tem. Porque isso acontece?
    Essa é provavelmente minha maior dúvida até agora, juntamente com a semelhança de resultados entre LR e RF.

    Pesquisando sobre o primeiro tópico (performance dos grupos bem/mal representados), achei uma que pode ser uma boa explicação para o que acontece aqui.
    Pegando o mesmo exemplo da coluna "tem_internet", é notório que a internet é um bem um tanto quanto acessível atualmente, então os 3590 alunos que estão no grupo B
    provavelmente estão espalhados por diversas classes sociais, indo de classe baixa para classe alta, então temos uma grande variação de alunos, o que torna
    a previsão indivídual mais difícil.
    Já o grupo A contempla aqueles que não possuem internet, que são muito provavelmente de uma classe social mais vulnerável, como pessoas com uma
    renda muito pequena ou até mesmo sem nenhuma renda. Portanto, é muito provável que as pessoas nesse grupo tenham uma nota menor, a homogeniedade nesse grupo é maior,
    fazendo com que seja mais fácil fazer uma previsão para esse grupo, mesmo com uma menor representação.
"""